### ISSUE TITLE
[US]: Pouvoir accèder aux donnée des panneaux solaires sur l'interface graphique java

### ISSUE THREAD

**Issue by Theor31** [IUT-Blagnac/sae-3-01-devapp-2024-2025-g1b5#26]
### User Story

En tant que client je souhaite pouvoir consulter les infos sur la production en éléctricité de mes panneaux solaires

### Importance

Must (Default)

### Critères d'acceptation

- Pouvoir choisir les informations à afficher
- Pouvoir visualiser les informations sous forme de graphique (pour l' évolution de la production en électricité sur la journée

### Tâches associées

- [ ] Écrire un test
- [ ] Coder
- [ ] Écrire la doc

**Comment by ClvSimon** [comment]
fin de l'accès aux panneaux solaires
