### ISSUE TITLE
[US]: 7. Laisser un message sur la FAQ

### ISSUE THREAD

**Issue by kwadjanib** [IUT-Blagnac/sae-3-01-devapp-2024-2025-g1b5#4]
### User Story

En tant que maman active, je veux pouvoir poser des questions spécifiques dans la FAQ pour obtenir des réponses directes à mes besoins.

### Importance

Should

### Critères d'acceptation

L'utilisateur doit pouvoir accéder à la section FAQ depuis le tableau de bord principal.

Un formulaire doit être disponible pour poser des questions, incluant des champs obligatoires 

L'utilisateur doit recevoir une confirmation que sa question a bien été envoyée.

### Tâches associées

- [ ] Écrire un test
- [ ] Coder
- [ ] Écrire la doc

**Comment by ClvSimon** [comment]
fin message faq via contact
